grafana:
  container_name: grafana
  hostname: grafana
  image: grafana/grafana
  restart: unless-stopped
  user: "0"
  ports:
    - "3000:3000"
  environment:
    - GF_PATHS_DATA=/var/lib/grafana
    - GF_PATHS_LOGS=/var/log/grafana
  volumes:
    - /mnt/influxdb/grafana/data:/var/lib/grafana
    - /mnt/influxdb/grafana/log:/var/log/grafana
