iobroker:
  image: buanet/iobroker:latest-v8
  container_name: iobroker
  hostname: iobroker
  privileged: true
  environment:
    - AVAHI="true"
    - SETUID=1000
    - SETGID=1000
  volumes:
    - ./volumes/iobroker:/opt/iobroker
  restart: unless-stopped
