influxdb:
  container_name: influxdb
  hostname: influxdb
  image: "influxdb:1.8"
  restart: unless-stopped
  ports:
    - "8086:8086"
  environment:
    - INFLUXDB_HTTP_FLUX_ENABLED=false
    - INFLUXDB_REPORTING_DISABLED=false
    - INFLUXDB_HTTP_AUTH_ENABLED=false
    - INFLUX_USERNAME=dba
    - INFLUX_PASSWORD=supremo
    - INFLUXDB_UDP_ENABLED=false
    - INFLUXDB_UDP_BIND_ADDRESS=0.0.0.0:8086
    - INFLUXDB_UDP_DATABASE=udp
    - INFLUXDB_DATA_QUERY_LOG_ENABLED=false
    - INFLUXDB_HTTP_LOG_ENABLED=false
  volumes:
    - /mnt/influxdb/data:/var/lib/influxdb
    - /mnt/influxdb/backup:/var/lib/influxdb/backup
